/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef __LIB_UTIL_UTIL_TDB_H__
#define __LIB_UTIL_UTIL_TDB_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from lib/util/util_tdb.c  */

int tdb_lock_bystring(struct tdb_context *tdb, const char *keyval);
void tdb_unlock_bystring(struct tdb_context *tdb, const char *keyval);
int tdb_read_lock_bystring(struct tdb_context *tdb, const char *keyval);
void tdb_read_unlock_bystring(struct tdb_context *tdb, const char *keyval);
int32_t tdb_fetch_int32_byblob(struct tdb_context *tdb, const char *keyval, size_t len);
int32_t tdb_fetch_int32(struct tdb_context *tdb, const char *keystr);
int tdb_store_int32_byblob(struct tdb_context *tdb, const char *keystr, size_t len, int32_t v);
int tdb_store_int32(struct tdb_context *tdb, const char *keystr, int32_t v);
BOOL tdb_fetch_uint32_byblob(struct tdb_context *tdb, const char *keyval, size_t len, uint32_t *value);
BOOL tdb_fetch_uint32(struct tdb_context *tdb, const char *keystr, uint32_t *value);
BOOL tdb_store_uint32_byblob(struct tdb_context *tdb, const char *keystr, size_t len, uint32_t value);
BOOL tdb_store_uint32(struct tdb_context *tdb, const char *keystr, uint32_t value);
int tdb_store_bystring(struct tdb_context *tdb, const char *keystr, TDB_DATA data, int flags);
TDB_DATA tdb_fetch_bystring(struct tdb_context *tdb, const char *keystr);
int tdb_delete_bystring(struct tdb_context *tdb, const char *keystr);
int32_t tdb_change_int32_atomic(struct tdb_context *tdb, const char *keystr, int32_t *oldval, int32_t change_val);
BOOL tdb_change_uint32_atomic(struct tdb_context *tdb, const char *keystr, uint32_t *oldval, uint32_t change_val);
int tdb_traverse_delete_fn(struct tdb_context *the_tdb, TDB_DATA key, TDB_DATA dbuf,
                     void *state);
size_t tdb_pack(TDB_CONTEXT *tdb, char *buf, int bufsize, const char *fmt, ...);
int tdb_unpack(TDB_CONTEXT *tdb, char *buf, int bufsize, const char *fmt, ...);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_UTIL_UTIL_TDB_H__ */

