/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef __AUTH_AUTH_SAM_H__
#define __AUTH_AUTH_SAM_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from auth/sam.c  */

_PUBLIC_ NTSTATUS authsam_account_ok(TALLOC_CTX *mem_ctx,
			    struct ldb_context *sam_ctx,
			    uint32_t logon_parameters,
			    struct ldb_message *msg,
			    struct ldb_message *msg_domain_ref,
			    const char *logon_workstation,
			    const char *name_for_logs);
_PUBLIC_ NTSTATUS authsam_make_server_info(TALLOC_CTX *mem_ctx, struct ldb_context *sam_ctx,
				  struct ldb_message *msg,
				  struct ldb_message *msg_domain_ref,
				  DATA_BLOB user_sess_key, DATA_BLOB lm_sess_key,
				  struct auth_serversupplied_info **_server_info);
_PUBLIC_ NTSTATUS sam_get_results_principal(struct ldb_context *sam_ctx,
				   TALLOC_CTX *mem_ctx, const char *principal,
				   struct ldb_message ***msgs,
				   struct ldb_message ***msgs_domain_ref);
NTSTATUS sam_get_server_info_principal(TALLOC_CTX *mem_ctx, const char *principal,
				       struct auth_serversupplied_info **server_info);

/* The following definitions come from auth/auth_sam_reply.c  */

NTSTATUS auth_convert_server_info_sambaseinfo(TALLOC_CTX *mem_ctx, 
					      struct auth_serversupplied_info *server_info, 
					      struct netr_SamBaseInfo **_sam);
NTSTATUS auth_convert_server_info_saminfo3(TALLOC_CTX *mem_ctx, 
					   struct auth_serversupplied_info *server_info, 
					   struct netr_SamInfo3 **_sam3);

/* The following definitions come from auth/ntlm_check.c  */

NTSTATUS hash_password_check(TALLOC_CTX *mem_ctx,
			     const struct samr_Password *client_lanman,
			     const struct samr_Password *client_nt,
			     const char *username, 
			     const struct samr_Password *stored_lanman, 
			     const struct samr_Password *stored_nt);
NTSTATUS ntlm_password_check(TALLOC_CTX *mem_ctx,
			     uint32_t logon_parameters,
			     const DATA_BLOB *challenge,
			     const DATA_BLOB *lm_response,
			     const DATA_BLOB *nt_response,
			     const char *username, 
			     const char *client_username, 
			     const char *client_domain,
			     const struct samr_Password *stored_lanman, 
			     const struct samr_Password *stored_nt, 
			     DATA_BLOB *user_sess_key, 
			     DATA_BLOB *lm_sess_key);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __AUTH_AUTH_SAM_H__ */

