/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef __LIB_CMDLINE_CREDENTIALS_H__
#define __LIB_CMDLINE_CREDENTIALS_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from lib/cmdline/credentials.c  */

void cli_credentials_set_cmdline_callbacks(struct cli_credentials *cred);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_CMDLINE_CREDENTIALS_H__ */

