/* autogenerated by build/smb_build/main.pl */
NTSTATUS dcerpc_server_netlogon_init (void);
NTSTATUS dcerpc_server_srvsvc_init (void);
NTSTATUS dcerpc_server_lsa_init (void);
NTSTATUS dcerpc_server_samr_init (void);
NTSTATUS dcerpc_server_epmapper_init (void);
NTSTATUS dcerpc_server_drsuapi_init (void);
NTSTATUS dcerpc_server_rpcecho_init (void);
NTSTATUS dcerpc_server_wkssvc_init (void);
NTSTATUS dcerpc_server_remote_init (void);
NTSTATUS dcerpc_server_spoolss_init (void);
NTSTATUS dcerpc_server_unixinfo_init (void);
NTSTATUS dcerpc_server_winreg_init (void);
NTSTATUS server_service_rpc_init (void);
NTSTATUS server_service_auth_init (void);
NTSTATUS server_service_kdc_init (void);
NTSTATUS server_service_smb_init (void);
NTSTATUS server_service_web_init (void);
NTSTATUS server_service_ldap_init (void);
NTSTATUS server_service_wrepl_init (void);
NTSTATUS server_service_nbtd_init (void);
NTSTATUS server_service_cldapd_init (void);
NTSTATUS server_service_winbind_init (void);
NTSTATUS process_model_single_init (void);
NTSTATUS process_model_standard_init (void);
NTSTATUS auth_sam_init (void);
//NTSTATUS auth_unix_init (void);
NTSTATUS auth_developer_init (void);
NTSTATUS auth_winbind_init (void);
NTSTATUS auth_anonymous_init (void);
NTSTATUS gensec_sasl_init (void);
NTSTATUS gensec_spnego_init (void);
NTSTATUS gensec_schannel_init (void);
NTSTATUS gensec_krb5_init (void);
NTSTATUS gensec_ntlmssp_init (void);
NTSTATUS gensec_gssapi_init (void);
NTSTATUS ntptr_simple_ldb_init (void);
NTSTATUS share_ldb_init (void);
NTSTATUS share_classic_init (void);
NTSTATUS registry_dir_init (void);
NTSTATUS registry_rpc_init (void);
NTSTATUS registry_w95_init (void);
NTSTATUS registry_ldb_init (void);
NTSTATUS registry_nt4_init (void);
NTSTATUS smb_setup_ejs_ldb (void);
NTSTATUS smb_setup_ejs_samba3 (void);
NTSTATUS smb_setup_ejs_random (void);
NTSTATUS smb_setup_ejs_nbt (void);
NTSTATUS smb_setup_ejs_config (void);
NTSTATUS smb_setup_ejs_auth (void);
NTSTATUS smb_setup_ejs_string (void);
NTSTATUS smb_setup_ejs_datablob (void);
NTSTATUS smb_setup_ejs_system (void);
NTSTATUS smb_setup_ejs_nss (void);
NTSTATUS ntvfs_simple_init (void);
NTSTATUS ntvfs_print_init (void);
NTSTATUS ntvfs_cifs_init (void);
NTSTATUS pvfs_acl_nfs4_init (void);
NTSTATUS pvfs_acl_xattr_init (void);
NTSTATUS ntvfs_posix_init (void);
NTSTATUS ntvfs_unixuid_init (void);
NTSTATUS ntvfs_cifs_posix_init (void);
NTSTATUS ntvfs_ipc_init (void);
NTSTATUS ntvfs_nbench_init (void);
int samldb_module_init (void);
int ldb_partition_init (void);
int ldb_skel_init (void);
int ldb_sort_init (void);
int rootdse_module_init (void);
int objectguid_module_init (void);
int wins_ldb_module_init (void);
int password_hash_module_init (void);
int ldb_objectclass_init (void);
int local_password_module_init (void);
int ldb_rdn_name_init (void);
int ldb_schema_init (void);
int ldb_kludge_acl_init (void);
int ldb_paged_results_init (void);
int ldb_operational_init (void);
int ldb_tdb_init (void);
int ldb_ildap_init (void);
int ldb_extended_dn_init (void);
int ldb_entryUUID_module_init (void);
int ldb_samba3sam_module_init (void);
int ldb_paged_searches_init (void);
int ldb_asq_init (void);
NTSTATUS torture_base_init (void);
NTSTATUS torture_smb2_init (void);
NTSTATUS torture_local_init (void);
NTSTATUS torture_nbt_init (void);
NTSTATUS torture_rpc_init (void);
NTSTATUS torture_rap_init (void);
NTSTATUS torture_raw_init (void);
NTSTATUS torture_nbench_init (void);
NTSTATUS torture_net_init (void);
NTSTATUS torture_dcom_init (void);
NTSTATUS torture_ldap_init (void);
NTSTATUS com_simple_init (void);
NTSTATUS sys_notify_inotify_init (void);

/* MODULE dcerpc_server INIT */
#define STATIC_dcerpc_server_MODULES { \
	dcerpc_server_netlogon_init, \
	dcerpc_server_srvsvc_init, \
	dcerpc_server_lsa_init, \
	dcerpc_server_samr_init, \
	dcerpc_server_epmapper_init, \
	dcerpc_server_drsuapi_init, \
	dcerpc_server_rpcecho_init, \
	dcerpc_server_wkssvc_init, \
	dcerpc_server_remote_init, \
	dcerpc_server_spoolss_init, \
	dcerpc_server_unixinfo_init, \
	dcerpc_server_winreg_init, \
	NULL \
 }

/* LIBRARY service INIT */
#define STATIC_service_MODULES { \
	server_service_rpc_init, \
	server_service_auth_init, \
	server_service_kdc_init, \
	server_service_smb_init, \
	server_service_web_init, \
	server_service_ldap_init, \
	server_service_wrepl_init, \
	server_service_nbtd_init, \
	server_service_cldapd_init, \
	server_service_winbind_init, \
	NULL \
 }

/* LIBRARY process_model INIT */
#define STATIC_process_model_MODULES { \
	process_model_single_init, \
	process_model_standard_init, \
	NULL \
 }

/* SUBSYSTEM auth INIT */
//auth_unix_init, 
#define STATIC_auth_MODULES { \
	auth_sam_init, \
	auth_developer_init, \
	auth_winbind_init, \
	auth_anonymous_init, \
	NULL \
 }
//gensec_sasl_init, 

/* LIBRARY gensec INIT */
#define STATIC_gensec_MODULES { \
	gensec_spnego_init, \
	gensec_schannel_init, \
	gensec_krb5_init, \
	gensec_ntlmssp_init, \
	gensec_gssapi_init, \
	NULL \
 }

/* LIBRARY ntptr INIT */
#define STATIC_ntptr_MODULES { \
	ntptr_simple_ldb_init, \
	NULL \
 }

/* LIBRARY share INIT */
#define STATIC_share_MODULES { \
	share_ldb_init, \
	share_classic_init, \
	NULL \
 }

/* LIBRARY registry INIT */
#define STATIC_registry_MODULES { \
	registry_dir_init, \
	registry_rpc_init, \
	registry_w95_init, \
	registry_ldb_init, \
	registry_nt4_init, \
	NULL \
 }

/* LIBRARY smbcalls INIT */
#define STATIC_smbcalls_MODULES { \
	smb_setup_ejs_ldb, \
	smb_setup_ejs_samba3, \
	smb_setup_ejs_random, \
	smb_setup_ejs_nbt, \
	smb_setup_ejs_config, \
	smb_setup_ejs_auth, \
	smb_setup_ejs_string, \
	smb_setup_ejs_datablob, \
	smb_setup_ejs_system, \
	smb_setup_ejs_nss, \
	NULL \
 }

/* LIBRARY ntvfs INIT */
#define STATIC_ntvfs_MODULES { \
	ntvfs_simple_init, \
	ntvfs_print_init, \
	ntvfs_cifs_init, \
	pvfs_acl_nfs4_init, \
	pvfs_acl_xattr_init, \
	ntvfs_posix_init, \
	ntvfs_unixuid_init, \
	ntvfs_cifs_posix_init, \
	ntvfs_ipc_init, \
	ntvfs_nbench_init, \
	NULL \
 }

/* LIBRARY ldb INIT */
#define STATIC_ldb_MODULES { \
	samldb_module_init, \
	ldb_partition_init, \
	ldb_skel_init, \
	ldb_sort_init, \
	rootdse_module_init, \
	objectguid_module_init, \
	wins_ldb_module_init, \
	password_hash_module_init, \
	ldb_objectclass_init, \
	local_password_module_init, \
	ldb_rdn_name_init, \
	ldb_schema_init, \
	ldb_kludge_acl_init, \
	ldb_paged_results_init, \
	ldb_operational_init, \
	ldb_tdb_init, \
	ldb_ildap_init, \
	ldb_extended_dn_init, \
	ldb_entryUUID_module_init, \
	ldb_samba3sam_module_init, \
	ldb_paged_searches_init, \
	ldb_asq_init, \
	NULL \
 }

/* SUBSYSTEM samba-socket INIT */
#define STATIC_samba_socket_MODULES { \
	NULL \
 }

/* LIBRARY torture INIT */
#define STATIC_torture_MODULES { \
	torture_base_init, \
	torture_smb2_init, \
	torture_local_init, \
	torture_nbt_init, \
	torture_rpc_init, \
	torture_rap_init, \
	torture_raw_init, \
	torture_nbench_init, \
	torture_net_init, \
	torture_dcom_init, \
	torture_ldap_init, \
	NULL \
 }

/* LIBRARY com INIT */
#define STATIC_com_MODULES { \
	com_simple_init, \
	NULL \
 }

/* SUBSYSTEM sys_notify INIT */
#define STATIC_sys_notify_MODULES { \
	sys_notify_inotify_init, \
	NULL \
 }
