/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef __LIB_DB_WRAP_PROTO_H__
#define __LIB_DB_WRAP_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from lib/db_wrap.c  */

char *wrap_casefold(void *context, void *mem_ctx, const char *s);
struct ldb_context *ldb_wrap_connect(TALLOC_CTX *mem_ctx,
				     const char *url,
				     struct auth_session_info *session_info,
				     struct cli_credentials *credentials,
				     unsigned int flags,
				     const char *options[]);
struct tdb_wrap *tdb_wrap_open(TALLOC_CTX *mem_ctx,
			       const char *name, int hash_size, int tdb_flags,
			       int open_flags, mode_t mode);

/* The following definitions come from lib/gendb.c  */

int gendb_search_v(struct ldb_context *ldb, 
		   TALLOC_CTX *mem_ctx,
		   struct ldb_dn *basedn,
		   struct ldb_message ***msgs,
		   const char * const *attrs,
		   const char *format, 
		   va_list ap)  _PRINTF_ATTRIBUTE(6,0);
int gendb_search(struct ldb_context *ldb,
		 TALLOC_CTX *mem_ctx, 
		 struct ldb_dn *basedn,
		 struct ldb_message ***res,
		 const char * const *attrs,
		 const char *format, ...) _PRINTF_ATTRIBUTE(6,7);
int gendb_search_dn(struct ldb_context *ldb,
		 TALLOC_CTX *mem_ctx, 
		 struct ldb_dn *dn,
		 struct ldb_message ***res,
		 const char * const *attrs);
int gendb_add_ldif(struct ldb_context *ldb, const char *ldif_string);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_DB_WRAP_PROTO_H__ */

