#ifndef __LIB_LDB_SAMBA_LDIF_HANDLERS_H__
#define __LIB_LDB_SAMBA_LDIF_HANDLERS_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from lib/ldb/samba/ldif_handlers.c  */

int ldb_register_samba_handlers(struct ldb_context *ldb);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_LDB_SAMBA_LDIF_HANDLERS_H__ */

