#ifndef __NBT_SERVER_WINS_WINSDB_PROTO_H__
#define __NBT_SERVER_WINS_WINSDB_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from nbt_server/wins/winsdb.c  */

uint64_t winsdb_get_maxVersion(struct winsdb_handle *h);
uint64_t winsdb_set_maxVersion(struct winsdb_handle *h, uint64_t newMaxVersion);
uint64_t winsdb_get_seqnumber(struct winsdb_handle *h);
struct winsdb_addr **winsdb_addr_list_make(TALLOC_CTX *mem_ctx);
struct winsdb_addr **winsdb_addr_list_add(struct winsdb_handle *h, const struct winsdb_record *rec,
					  struct winsdb_addr **addresses, const char *address,
					  const char *wins_owner, time_t expire_time,
					  BOOL is_name_registration);
void winsdb_addr_list_remove(struct winsdb_addr **addresses, const char *address);
struct winsdb_addr *winsdb_addr_list_check(struct winsdb_addr **addresses, const char *address);
size_t winsdb_addr_list_length(struct winsdb_addr **addresses);
const char **winsdb_addr_string_list(TALLOC_CTX *mem_ctx, struct winsdb_addr **addresses);
NTSTATUS winsdb_lookup(struct winsdb_handle *h, 
		       struct nbt_name *name,
		       TALLOC_CTX *mem_ctx,
		       struct winsdb_record **_rec);
NTSTATUS winsdb_record(struct winsdb_handle *h, struct ldb_message *msg, TALLOC_CTX *mem_ctx, time_t now, struct winsdb_record **_rec);
struct ldb_message *winsdb_message(struct ldb_context *ldb, 
				   struct winsdb_record *rec, TALLOC_CTX *mem_ctx);
uint8_t winsdb_add(struct winsdb_handle *h, struct winsdb_record *rec, uint32_t flags);
uint8_t winsdb_modify(struct winsdb_handle *h, struct winsdb_record *rec, uint32_t flags);
uint8_t winsdb_delete(struct winsdb_handle *h, struct winsdb_record *rec);
struct winsdb_handle *winsdb_connect(TALLOC_CTX *mem_ctx, enum winsdb_handle_caller caller);

/* The following definitions come from nbt_server/wins/wins_hook.c  */

void wins_hook(struct winsdb_handle *h, const struct winsdb_record *rec, enum wins_hook_action action);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __NBT_SERVER_WINS_WINSDB_PROTO_H__ */

