/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef __LIB_SOCKET_NETIF_PROTO_H__
#define __LIB_SOCKET_NETIF_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from lib/socket/interface.c  */

void unload_interfaces(void);
int iface_count(void);
const char *iface_n_ip(int n);
const char *iface_n_bcast(int n);
const char *iface_n_netmask(int n);
const char *iface_best_ip(const char *dest);
BOOL iface_is_local(const char *dest);
BOOL iface_same_net(const char *ip1, const char *ip2, const char *netmask);

/* The following definitions come from lib/socket/netif.c  */

int get_interfaces(struct iface_struct *ifaces, int max_interfaces);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_SOCKET_NETIF_PROTO_H__ */

