#ifndef __AUTH_GENSEC_SCHANNEL_PROTO_H__
#define __AUTH_GENSEC_SCHANNEL_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from auth/gensec/schannel.c  */

_PUBLIC_ NTSTATUS dcerpc_schannel_creds(struct gensec_security *gensec_security,
			       TALLOC_CTX *mem_ctx,
			       struct creds_CredentialState **creds);
NTSTATUS gensec_schannel_init(void);

/* The following definitions come from auth/gensec/schannel_sign.c  */

NTSTATUS schannel_unseal_packet(struct gensec_security *gensec_security, 
				TALLOC_CTX *mem_ctx, 
				uint8_t *data, size_t length, 
				const uint8_t *whole_pdu, size_t pdu_length, 
				const DATA_BLOB *sig);
NTSTATUS schannel_check_packet(struct gensec_security *gensec_security, 
			       TALLOC_CTX *mem_ctx, 
			       const uint8_t *data, size_t length, 
			       const uint8_t *whole_pdu, size_t pdu_length, 
			       const DATA_BLOB *sig);
NTSTATUS schannel_seal_packet(struct gensec_security *gensec_security, 
			      TALLOC_CTX *mem_ctx, 
			      uint8_t *data, size_t length, 
			      const uint8_t *whole_pdu, size_t pdu_length, 
			      DATA_BLOB *sig);
NTSTATUS schannel_sign_packet(struct gensec_security *gensec_security, 
			      TALLOC_CTX *mem_ctx, 
			      const uint8_t *data, size_t length, 
			      const uint8_t *whole_pdu, size_t pdu_length, 
			      DATA_BLOB *sig);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __AUTH_GENSEC_SCHANNEL_PROTO_H__ */

