/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef __AUTH_GENSEC_SCHANNEL_STATE_H__
#define __AUTH_GENSEC_SCHANNEL_STATE_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from auth/gensec/schannel_state.c  */

struct ldb_context *schannel_db_connect(TALLOC_CTX *mem_ctx);
NTSTATUS schannel_store_session_key_ldb(TALLOC_CTX *mem_ctx,
					struct ldb_context *ldb,
					struct creds_CredentialState *creds);
NTSTATUS schannel_store_session_key(TALLOC_CTX *mem_ctx,
				    struct creds_CredentialState *creds);
NTSTATUS schannel_fetch_session_key_ldb(TALLOC_CTX *mem_ctx,
					struct ldb_context *ldb,
					const char *computer_name, 
					const char *domain,
					struct creds_CredentialState **creds);
NTSTATUS schannel_fetch_session_key(TALLOC_CTX *mem_ctx,
					const char *computer_name, 
					const char *domain, 
					struct creds_CredentialState **creds);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __AUTH_GENSEC_SCHANNEL_STATE_H__ */

