#ifndef __AUTH_GENSEC_SPNEGO_PROTO_H__
#define __AUTH_GENSEC_SPNEGO_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from auth/gensec/spnego.c  */

NTSTATUS gensec_spnego_init(void);

/* The following definitions come from auth/gensec/spnego_parse.c  */

ssize_t spnego_read_data(DATA_BLOB data, struct spnego_data *token);
ssize_t spnego_write_data(TALLOC_CTX *mem_ctx, DATA_BLOB *blob, struct spnego_data *spnego);
BOOL spnego_free_data(struct spnego_data *spnego);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __AUTH_GENSEC_SPNEGO_PROTO_H__ */

